deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: pypi-AgENdGVzdC5weXBpLm9yZwIkZWVkODliZDktMzJkMy00N2E3LWJhYmQtZTQ0ZDgzNDBmZWFhAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiALfiWktZVHjMfsUDdXY41AVK_rVcIc4TYw3Ld-EXidYA
  on:
    tags: true
language: python
rvm:
 - 3.8